### ISSUE TITLE
failed node merge in witness graph (false positive)

### ISSUE THREAD

**Issue by smisch** [smisch/deciding-isotactics#1]
working alignment (possibly false positive):
1: ae - s
2: bc - t
3: c - t
4: d - u
5: f - v

failing alignment (remove 3: c-t):
1: ae - s
2: bc - t
4: d - u
5: f - v

Expected behavior:

- Merge nodes [3,III,bc-t] and [4,III,bc-t] since they both have the same parent [2,II,ae-s] and share the same edge label.
- output non-iso, since for example trace acef in m1 => {{ae}}{{bc}{c}}{{ae}}{{f}} => (1)(2,3)(1)(5) is not realizable (with m2 trace stuv)
![gegenbeispiel](https://user-images.githubusercontent.com/5692146/29668074-2f171ef4-88df-11e7-8299-c422d3f501b2.png)
[Gegenbeispiel.zip](https://github.com/smisch/deciding-isotactics/files/1248903/Gegenbeispiel.zip)

**Comment by artempolyvyanyy** [comment]
The top alignment (with 3: c - t) does not induce isotactics as tactics of runs <a,c,e,f> and <s,t,u,v> cannot be aligned. Note, however, that relation "3: c - t" is subsumed by "2: bc - t". Hence, it is redundant. Still, the tool should work even for alignments with such "redundant" relations and, thus, this is an open issue.

**Comment by smisch** [comment]
After the recent changes this example does not crash anymore and properly outputs "no" for isotactics. Both the left and right witness graph reports different behavior.
