### ISSUE TITLE
crash-example-1

### ISSUE THREAD

**Issue by smisch** [smisch/deciding-isotactics#2]
iso-decision exits prematurely with a segmentation fault (invalid memory access). 

![all](https://user-images.githubusercontent.com/5692146/30033428-822f8f44-919b-11e7-8bba-78fbdb524483.png)
[crash-example-1.zip](https://github.com/smisch/deciding-isotactics/files/1275151/crash-example-1.zip)

**Comment by artempolyvyanyy** [comment]
The automaton on the left covers the tactics of the automaton on the right. However, the two proposed automata are not isotactic. Trace a,c,e,f cannot be covered by the automaton on the right.

**Comment by smisch** [comment]
**Reason for the Crash** 
- in DetWitnessUtils.cpp
- DWG::findAllNodesRhs (and probably also DWG::findAllNodesLhs) uses a range-based loop
- which creates an implicit vector iterator
- during the iteration adds new elements to this vector
- thereby invalidating all existing iterators
- leading to an invalid memory access for some executions

```c++
void DWG::findAllNodesRhs(DWG::Vertex &v, const WG_t &wg)
{
  // range-based for loop creates an implicit iterator for v.vs
  for (const WG::vDesc &start : v.vs) {

    // [..]

    // this adds a new element to v.vs, thereby invalidating the implicit iterator. 
    // start may point to an invalid memory location on the next iteration. 
    DWG::addVertexToSet(v, nv, wg);
```

**Proposed Solution** 
Switch from the range-based loop (based on iterator) to an index-based loop or use a queue.
