### ISSUE TITLE
crash-example-2 (labels missing from the alignment)

### ISSUE THREAD

**Issue by smisch** [smisch/deciding-isotactics#3]
If an alignment doesn't contain all labels used by the two state machines iso-decision will crash with a segmentation fault (invalid memory access). In this example the alignment is just {a~s} and is missing the label "b". 
The expected behavior may be an open issue. 

- One possibility is that label "b" should be ignored, but the implementation of the witness graph may not allow this, yet.
- Another possibility would be to reject alignments if they are missing labels and exit with an error (invalid alignment). 
- Finally depending on the definition of isotactics, iso-decision could also return "no", meaning the two state machines are not in isotactics if labels are missing.  

![all](https://user-images.githubusercontent.com/5692146/30033585-5881beb4-919c-11e7-9e1a-d3f3c7ffad57.png)
[crash-example-2.zip](https://github.com/smisch/deciding-isotactics/files/1275164/crash-example-2.zip)

**Comment by artempolyvyanyy** [comment]
The first bullet point specifies the intended behavior, i.e., label "b" should be ignored. Hence, the two proposed automata are isotactic w.r.t. the given alignment. Because "b" is not participating in the alignment, it should be treated as a silent step.

**Comment by smisch** [comment]
**Reason for the Crash**
The implementation did not handle the case where a label is not an element of any group of the alignment. In the above example there is no alignment group that contains the label "b". 

**Proposed Solution**
In the determinization step treat such labels as "epsilon" and eliminate these edges via epsilon-closure. Attached example shows the desired behavior. 
![all](https://user-images.githubusercontent.com/5692146/30554187-ee83e420-9ca3-11e7-9f64-1b02991817a1.png)
The input graph m1 is first determinized into det(m1). The edges with labels "a" and "b" are merged into one edge "{a,b}" simply called "a" in det(m1). Therefore the vertices "2" and "3" are merged into "{2,3}". 
The edges with labels "e" are treated as epsilon edges because "e" is not contained in any alignment group. Therefore vertices "4" is also merged into "{2,3}" resulting in "{2,3,4}". 

For the above example the following image shows the desired behavior: 
![all](https://user-images.githubusercontent.com/5692146/30554386-a9ea47c2-9ca4-11e7-9617-39f53966fd7d.png)

The two graphics are generated via the already fixed iso-decision algorithm. The fix also includes the prevention of vertex sets containing duplicates, i.e. vertices called "{3,3}" will now only be called "{3}".
